########################
# Grafana Configuration
########################

[paths]
data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins

[server]
protocol = http
http_port = 3000
domain = localhost
enforce_domain = false
root_url = %(protocol)s://%(domain)s:%(http_port)s/

[security]
admin_user = admin
admin_password = admin
# Allow embedding Grafana panels
allow_embedding = true
cookie_secure = false
disable_gravatar = true

[users]
allow_sign_up = false
allow_org_create = false
default_theme = dark

[auth]
disable_login_form = false
disable_signout_menu = false

[auth.anonymous]
enabled = false

[auth.basic]
enabled = true

[analytics]
reporting_enabled = false
check_for_updates = true

[log]
mode = console
level = info

[dashboards]
versions_to_keep = 20

[alerting]
enabled = true
execute_alerts = true

[unified_alerting]
enabled = true

[smtp]
enabled = false

################################
# End of Grafana configuration #
################################
